# -*- coding: utf-8 -*-

import os
import json
import time
import html
import re
from pathlib import Path
from typing import Any, Dict, List, Optional
import xml.etree.ElementTree as ET

import requests


# =========================================================
# Config
# =========================================================
# Read FULL query files generated by build_queries.py
INPUT_DIR = Path("")

# Put this run's outputs into a NEW folder tree
RUN_ROOT = Path("")#retrieval_full_docs_run
CACHE_DIR = RUN_ROOT / "cache"
DOCS_DIR = RUN_ROOT / "docs"
LOG_DIR = RUN_ROOT / "logs"

CACHE_DIR.mkdir(parents=True, exist_ok=True)
DOCS_DIR.mkdir(parents=True, exist_ok=True)
LOG_DIR.mkdir(parents=True, exist_ok=True)

QUERY_CACHE_DIR = CACHE_DIR / "queries"
PMID_CACHE_DIR = CACHE_DIR / "pmids"
QUERY_CACHE_DIR.mkdir(parents=True, exist_ok=True)
PMID_CACHE_DIR.mkdir(parents=True, exist_ok=True)

ESEARCH_URL = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi"
EFETCH_URL = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi"

DEFAULT_TOOL = "med_retrieval_pipeline_full"
DEFAULT_RETMAX = 20
REQUEST_TIMEOUT = 40

# This script is FULL ONLY
USE_SMALL_FILES = False

# Full query inputs only
INPUT_FILES = [
    "medqa_train_queries.jsonl",
    "medqa_validation_queries.jsonl",
    "medqa_test_queries.jsonl",
    "medmcqa_train_queries.jsonl",
    "medmcqa_validation_queries.jsonl",
    "medmcqa_test_queries.jsonl",
    "pubmedqa_train_queries.jsonl",
]

# Refresh switches
FORCE_REFRESH_QUERY = False
FORCE_REFRESH_PMID = False
RETMAX = 20
LOG_FILENAME = "retrieve_pubmed_full.log"


# =========================================================
# Basic helpers
# =========================================================
def normalize_text(x: Any) -> str:
    if x is None:
        return ""
    s = str(x)
    s = re.sub(r"\s+", " ", s).strip()
    return s


def safe_filename(text: str) -> str:
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", str(text))


def read_jsonl(path: Path) -> List[Dict[str, Any]]:
    rows = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            rows.append(json.loads(line))
    return rows


def write_json(path: Path, obj: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(obj, f, ensure_ascii=False, indent=2)


def write_jsonl(path: Path, rows: List[Dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")


def load_json_if_exists(path: Path) -> Optional[Dict[str, Any]]:
    if not path.exists():
        return None
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def save_log(msg: str, filename: str = LOG_FILENAME) -> None:
    log_path = LOG_DIR / filename
    with log_path.open("a", encoding="utf-8") as f:
        f.write(msg.rstrip() + "\n")


# =========================================================
# PubMed client
# =========================================================
class PubMedClient:
    def __init__(
        self,
        email: str,
        api_key: Optional[str] = None,
        tool: str = DEFAULT_TOOL,
        timeout: int = REQUEST_TIMEOUT,
    ):
        self.email = email
        self.api_key = api_key
        self.tool = tool
        self.timeout = timeout
        self.session = requests.Session()

        self.base_params = {
            "tool": self.tool,
            "email": self.email,
        }
        if self.api_key:
            self.base_params["api_key"] = self.api_key

        # no key <= ~3 req/s ; with key <= ~10 req/s
        self.sleep_seconds = 0.12 if self.api_key else 0.40

    def _request(self, url: str, params: Dict[str, Any]) -> requests.Response:
        full_params = {**self.base_params, **params}
        resp = self.session.get(url, params=full_params, timeout=self.timeout)
        resp.raise_for_status()
        time.sleep(self.sleep_seconds)
        return resp

    def esearch_pubmed(self, query: str, retmax: int = DEFAULT_RETMAX) -> List[str]:
        params = {
            "db": "pubmed",
            "term": query,
            "retmax": str(retmax),
            "retmode": "json",
            "sort": "relevance",
        }
        resp = self._request(ESEARCH_URL, params)
        data = resp.json()
        idlist = data.get("esearchresult", {}).get("idlist", [])
        return [str(x) for x in idlist]

    def efetch_pubmed(self, pmids: List[str]) -> List[Dict[str, Any]]:
        if not pmids:
            return []

        params = {
            "db": "pubmed",
            "id": ",".join(pmids),
            "retmode": "xml",
        }
        resp = self._request(EFETCH_URL, params)
        return parse_pubmed_xml(resp.text)


# =========================================================
# XML parsing
# =========================================================
def extract_year_from_pubdate(pub_date_elem: Optional[ET.Element]) -> Optional[str]:
    if pub_date_elem is None:
        return None

    year_elem = pub_date_elem.find("Year")
    if year_elem is not None and year_elem.text:
        return year_elem.text.strip()

    medline_date = pub_date_elem.find("MedlineDate")
    if medline_date is not None and medline_date.text:
        m = re.search(r"\b(19|20)\d{2}\b", medline_date.text)
        if m:
            return m.group(0)

    return None


def get_abstract_text(article_elem: ET.Element) -> str:
    abstract = article_elem.find(".//Abstract")
    if abstract is None:
        return ""

    texts = []
    for abstract_text in abstract.findall("AbstractText"):
        label = abstract_text.attrib.get("Label")
        content = "".join(abstract_text.itertext()).strip()
        content = normalize_text(html.unescape(content))
        if not content:
            continue
        if label:
            texts.append(f"{label}: {content}")
        else:
            texts.append(content)

    return "\n".join(texts).strip()


def parse_pubmed_xml(xml_text: str) -> List[Dict[str, Any]]:
    root = ET.fromstring(xml_text)
    records = []

    for article in root.findall(".//PubmedArticle"):
        pmid_elem = article.find(".//MedlineCitation/PMID")
        article_title_elem = article.find(".//Article/ArticleTitle")
        journal_title_elem = article.find(".//Article/Journal/Title")
        pub_date_elem = article.find(".//Article/Journal/JournalIssue/PubDate")

        pmid = "".join(pmid_elem.itertext()).strip() if pmid_elem is not None else ""
        title = "".join(article_title_elem.itertext()).strip() if article_title_elem is not None else ""
        journal = "".join(journal_title_elem.itertext()).strip() if journal_title_elem is not None else ""

        title = normalize_text(html.unescape(title))
        journal = normalize_text(html.unescape(journal))
        year = extract_year_from_pubdate(pub_date_elem)
        abstract = get_abstract_text(article)

        records.append({
            "pmid": pmid,
            "title": title,
            "abstract": abstract,
            "journal": journal,
            "year": year,
        })

    return records


# =========================================================
# Cache helpers
# =========================================================
def query_cache_path(qid: str) -> Path:
    return QUERY_CACHE_DIR / f"{safe_filename(qid)}.json"


def pmid_cache_path(pmid: str) -> Path:
    return PMID_CACHE_DIR / f"{safe_filename(pmid)}.json"


def load_query_cache(qid: str) -> Optional[Dict[str, Any]]:
    return load_json_if_exists(query_cache_path(qid))


def save_query_cache(qid: str, payload: Dict[str, Any]) -> None:
    write_json(query_cache_path(qid), payload)


def load_pmid_cache(pmid: str) -> Optional[Dict[str, Any]]:
    return load_json_if_exists(pmid_cache_path(pmid))


def save_pmid_cache(pmid: str, payload: Dict[str, Any]) -> None:
    write_json(pmid_cache_path(pmid), payload)


# =========================================================
# Retrieval pipeline
# =========================================================
def retrieve_pmids_for_record(
    record: Dict[str, Any],
    client: PubMedClient,
    retmax: int = DEFAULT_RETMAX,
    force_refresh_query: bool = False,
) -> List[str]:
    qid = record["qid"]

    query_candidates = record.get("query_candidates", None)
    if not isinstance(query_candidates, list) or not query_candidates:
        query_candidates = [
            normalize_text(record.get("query_primary", record.get("query", ""))),
            normalize_text(record.get("query_fallback", "")),
        ]

    query_candidates = [normalize_text(q) for q in query_candidates if normalize_text(q)]
    query_candidates = list(dict.fromkeys(query_candidates))

    if not query_candidates:
        return []

    if not force_refresh_query:
        cached = load_query_cache(qid)
        if cached is not None:
            cached_pmids = cached.get("pmids", [])
            if isinstance(cached_pmids, list) and len(cached_pmids) > 0:
                return [str(x) for x in cached_pmids]

    used_query = ""
    pmids = []

    for q in query_candidates:
        pmids = client.esearch_pubmed(q, retmax=retmax)
        if pmids:
            used_query = q
            break

    cache_payload = {
        "qid": qid,
        "dataset": record.get("dataset", ""),
        "split": record.get("split", ""),
        "query": used_query,
        "query_candidates": query_candidates,
        "pmids": pmids,
        "retmax": retmax,
    }
    save_query_cache(qid, cache_payload)
    return pmids


def fetch_docs_for_pmids(
    pmids: List[str],
    client: PubMedClient,
    force_refresh_pmid: bool = False,
) -> List[Dict[str, Any]]:
    missing_pmids = []

    for pmid in pmids:
        if not force_refresh_pmid:
            cached = load_pmid_cache(pmid)
            if cached is not None:
                continue
        missing_pmids.append(pmid)

    if missing_pmids:
        fetched = client.efetch_pubmed(missing_pmids)
        for doc in fetched:
            pmid = str(doc.get("pmid", "")).strip()
            if pmid:
                save_pmid_cache(pmid, doc)

    docs = []
    for pmid in pmids:
        cached = load_pmid_cache(pmid)
        if cached is not None:
            docs.append(cached)

    return docs


def build_docs_record(
    query_record: Dict[str, Any],
    pmids: List[str],
    docs: List[Dict[str, Any]],
) -> Dict[str, Any]:
    return {
        "qid": query_record.get("qid", ""),
        "dataset": query_record.get("dataset", ""),
        "split": query_record.get("split", ""),
        "question": query_record.get("question", ""),
        "options": query_record.get("options", {}),
        "answer": query_record.get("answer", ""),
        "answer_text": query_record.get("answer_text", ""),
        "context": query_record.get("context", ""),
        "query": query_record.get("query", ""),
        "query_primary": query_record.get("query_primary", ""),
        "query_fallback": query_record.get("query_fallback", ""),
        "query_candidates": query_record.get("query_candidates", []),
        "pmids": pmids,
        "retrieved_docs": docs,
    }


def process_one_input_file(
    input_path: Path,
    output_path: Path,
    client: PubMedClient,
    retmax: int = DEFAULT_RETMAX,
    force_refresh_query: bool = False,
    force_refresh_pmid: bool = False,
) -> None:
    rows = read_jsonl(input_path)
    out_rows = []

    print(f"\n[INFO] Processing: {input_path.name}")
    save_log(f"\n[INFO] Processing: {input_path.name}")

    for idx, record in enumerate(rows, start=1):
        qid = record.get("qid", "")
        query_preview = normalize_text(record.get("query_primary", record.get("query", "")))

        try:
            pmids = retrieve_pmids_for_record(
                record=record,
                client=client,
                retmax=retmax,
                force_refresh_query=force_refresh_query,
            )

            docs = fetch_docs_for_pmids(
                pmids=pmids,
                client=client,
                force_refresh_pmid=force_refresh_pmid,
            )

            out_record = build_docs_record(
                query_record=record,
                pmids=pmids,
                docs=docs,
            )
            out_rows.append(out_record)

            if idx % 20 == 0 or idx == len(rows):
                msg = (
                    f"[{idx:>5}/{len(rows):>5}] {qid} | "
                    f"pmids={len(pmids):>2} | docs={len(docs):>2} | "
                    f"query={query_preview[:100]}"
                )
                print(msg)
                save_log(msg)

        except Exception as e:
            err = f"[ERROR] qid={qid} | query={query_preview[:120]} | error={e}"
            print(err)
            save_log(err)

            out_rows.append({
                "qid": qid,
                "dataset": record.get("dataset", ""),
                "split": record.get("split", ""),
                "question": record.get("question", ""),
                "options": record.get("options", {}),
                "answer": record.get("answer", ""),
                "answer_text": record.get("answer_text", ""),
                "context": record.get("context", ""),
                "query": record.get("query", ""),
                "query_primary": record.get("query_primary", ""),
                "query_fallback": record.get("query_fallback", ""),
                "query_candidates": record.get("query_candidates", []),
                "pmids": [],
                "retrieved_docs": [],
                "error": str(e),
            })

    write_jsonl(output_path, out_rows)
    print(f"[OK] Saved docs: {output_path}")
    save_log(f"[OK] Saved docs: {output_path}")


def main() -> None:
    email = os.environ.get("NCBI_EMAIL", "").strip()
    api_key = os.environ.get("NCBI_API_KEY", "").strip()

    if not email:
        raise ValueError("NCBI_EMAIL is not set. Please export NCBI_EMAIL first.")

    client = PubMedClient(
        email=email,
        api_key=api_key if api_key else None,
        tool=DEFAULT_TOOL,
    )

    print("========== Retrieving PubMed docs (FULL only) ==========")
    print(f"NCBI_EMAIL = {email}")
    print(f"API key set = {'YES' if api_key else 'NO'}")
    print(f"USE_SMALL_FILES = {USE_SMALL_FILES}")
    print(f"RUN_ROOT = {RUN_ROOT}")
    print(f"DOCS_DIR = {DOCS_DIR}")
    print(f"CACHE_DIR = {CACHE_DIR}")
    print(f"LOG_DIR = {LOG_DIR}")
    print(f"RETMAX = {RETMAX}")
    print(f"FORCE_REFRESH_QUERY = {FORCE_REFRESH_QUERY}")
    print(f"FORCE_REFRESH_PMID = {FORCE_REFRESH_PMID}")

    for fn in INPUT_FILES:
        input_path = INPUT_DIR / fn
        if not input_path.exists():
            print(f"[WARN] Missing input file: {input_path}")
            continue

        output_path = DOCS_DIR / fn.replace("_queries.jsonl", "_docs.jsonl")

        process_one_input_file(
            input_path=input_path,
            output_path=output_path,
            client=client,
            retmax=RETMAX,
            force_refresh_query=FORCE_REFRESH_QUERY,
            force_refresh_pmid=FORCE_REFRESH_PMID,
        )

    print("\nDone.")


if __name__ == "__main__":
    main()

